# Generated by Django 3.0.6 on 2020-05-25 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=10)),
                ('tz', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('foriegn_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_periods', to='Apiend.user')),
            ],
        ),
    ]
