# Generated by Django 3.0.6 on 2020-05-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apiend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.CharField(max_length=40),
        ),
    ]
